companies = [
    "Mojang Studios",
    "Electronic Arts",
    "Riot Games",
    "Valve",
    "Epic Games",
    "Roblox",
    "Bungie",
    "CD Projekt Red",
    "Larian Studios",
    "Supercell"
    "GitHub",
    "GitLab",
    "HashiCorp",
    "Docker",
    "JetBrains",
    "Postman",
    "Vercel",
    "Render",
    "Fly.io"
    "Cloudflare",
    "Datadog",
    "Elastic",
    "Confluent",
    "Snowflake",
    "MongoDB",
    "Redis",
    "DigitalOcean",
    "Figma",
    "Canva",
    "Framer",
    "Webflow",
    "Discord",
    "Reddit",
    "Notion",
    "Linear",
    "Obsidian",
    "Anthropic",
    "Hugging Face",
    "Perplexity",
    "Cursor"    
]

