companies = [
    "Roblox",
    "GitLab",
    "JetBrains",
    "Postman",
    "Vercel",
    "Cloudflare",
    "Datadog",
    "Elastic",
    "MongoDB",
    "Figma",
    "Webflow",
    "Discord",
    "Reddit",
    "Anthropic",
]